image: node:20

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - cd server
    - npm ci
<<<<<<< HEAD
  artifacts:
    paths:
      - server/node_modules/

test-job:
  stage: test
  script:
    - cd server
=======
>>>>>>> b7dff287993dd0c3763478a0eb2ff8fdebeb2992
    - npm run eslint
    - npm test
  dependencies:
    - build-job

deploy-job:
  stage: deploy
  script:
    - echo "Deploying to production server..."
  when: manual
  only:
    - main