image: node:20

stages:
  - test

test_job:
  stage: test
  script:
    - cd server
    - npm ci
    - npm run eslint || echo "Linter hittade problem, men vi fortsätter"
    - npm test
    - npm audit --audit-level=high
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"