image: node:20


stages:
  - validate

test_and_scan:
  stage: validate
  script:
    - cd server
    - npm ci
    - npm run lint || echo "Ingen linter konfigurerad"
    - npm test
    - npm audit --audit-level=high
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"