version: '3.8'

services:
  app:
    build: ./server 
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://db:27017/quiznote
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: #
      - quiznote-data:/data/db #

volumes:
  quiznote-data: #