version: '3.8'

services:
  app:
    build: ./server 
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb+srv://an225ee_db_user:3wI6DijWwn5JywvX@cluster1.o1dz1am.mongodb.net/?appName=Cluster1
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: #
      - quiznote-data:/data/db #

volumes:
  quiznote-data: #